### ISSUE TITLE
Inconsistent memory usage

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#100]
Some parts of the code, in particular the Sema uses custom allocation (bump allocation?). However, this is not true for the many other parts of the code which instead have regular allocation, followed by compaction in a copy turning std::vectors into plain pointer arrays.

This needs to be unified. Taking a page from other compilers, it makes sense that all allocations use a bump allocator, possibly with a simple free list, but unlike C++ where huge amounts of headers needs to be parsed again and again, C2 is unlikely to have a problem with this.

**Comment by bvdberg** [comment]
Why do we need to unify this? The entire AST uses optimized, custom allocation, the rest doesn't.

**Comment by lerno** [comment]
Incorrect. The parser is full of std::vector usage. E.g. ParseCompoundStatement, ParseAsmStatement, ParseFunctionParams etc etc

**Comment by bvdberg** [comment]
std::vector is indeed used in the parser as a Temporary storage, but it's never used in the actual AST.
It is sometimes passed to Sema (now ASTBuilder) but there it's converted. For an example, see
ASTBuilder::ActOnStructMembers().

**Comment by lerno** [comment]
Yes, that was my point.

**Comment by bvdberg** [comment]
The issue they solve is that the AST stores member pointers as a continuous array, while during
parsing we don't know how many will be parsed. So the std::vector solves this part..

**Comment by lerno** [comment]
What I mean is that maybe a simple resizable vector implementation would be sufficient for this. In addition, such an implementation could provide the conversion to pointer array.
