### ISSUE TITLE
Proposal to `then {} else {}` after a loop

### ISSUE THREAD

**Issue by thanhminhmr** [c2lang/c2compiler#107]
Currently, things look like this:
```
bool isOK = true;
for (i8 index = 0; index < 10; index++) {
    if (doSomething(index) == false) {
        isOK = false;
        break;
    }
}
if (isOK) {
    finishTheJob();
} else {
    screamAndThrowEverything();
}
```
With the `then {} else {}`, things should look like this:
```
for (i8 index = 0; index < 10; index++) {
    if (doSomething(index) == false) break;
} then {
    finishTheJob();
} else {
    screamAndThrowEverything();
}
```
The similar syntax should be the same with `while` and `do while` loop.
This should make the code shorter but easier to understand, remove the necessity for the extra `bool` and should speed things up a bit compared to the `if then` version (remove the extra `bool` and the condition check).
Personally I meet a lot of case where I wish this syntax is a thing. What do everyone think about this idea?

**Comment by lerno** [comment]
I would usually refactor this as:

```
bool helper_func() {
   for (i8 index = 0; index < 10; index++) {
      if (!doSomething(index)) return false;
   }
   return true;
}

...
if (helper_func()) {
  finishTheJob();
} else {
   screamAndThrowEverything();
}
```

There are three alternative possibilites that comes to mind if one wanted to solve this in some more uniform manner:

1. All statments return a value
2. Statment expressions
3. Inner functions (or anonymous) functions.

With the third, the code could look like this:

```
func void do_job() {
   load_jobs();
   
   func bool helper() {
      for (i8 index = 0; index < 10; index++) {
         if (!doSomething(index)) return false;
      }
      return true;
   }
   
   if (helper()) {
      finishTheJob();
   } else {
      screamAndThrowEverything();
   }
   cleanup_jobs();
}
```

**Comment by bvdberg** [comment]
I think the meaning of a for/while/etc loop should be a loop and not have a conditional meaning
at the end. In my opinion this only makes the languages more complex, while it should consist of
easy to understand operations.
