### ISSUE TITLE
Unable to build C2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by rzuckerm** [c2lang/c2compiler#122]
I've followed the installation instructions, and I'm getting this error when I run `make`:

```
/usr/bin/ld: CMakeFiles/c2c.dir/Builder/PluginManager.cpp.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
```

Any idea how to fix this?

**Comment by bvdberg** [comment]
This archive is obsolete. The new version of the C2 compiler can be found in https://github.com/c2lang/c2c_native.
