### ISSUE TITLE
Simpler syntax for functions and methods

### ISSUE THREAD

**Issue by chqrlie** [c2lang/c2compiler#130]
`struct` functions are very useful and improves readability at call sites.

Yet the method definition is a bit redundant and cumbersome.

You could infer the type of the first argument if not specified:
```
public fn void Tokenizer.lex(Tokenizer* t, Token* result)
```
Could be written
```
public fn void Tokenizer.lex(t, Token* result)
```
`t` could be `this` or `self` according to the programmers choice.

Another simplification you chose to implement for empty argument lists, stripping the `void` from `(void)` could be applied to the return type: just omit the `void` if the function has no return type.  This would further simplify the above method to:
```
public fn Tokenizer.lex(this, Token* result)
```

**Comment by lerno** [comment]
This is actually somewhat ambiguous since "static" struct methods are valid, eg `public fn Tokenizer.new(char* data) { ... }`.

**Comment by bvdberg** [comment]
Yes, I agree that struct functions are a bit long to write. Also some function are passed a const ptr, others a non-const..
Let's think about this some more..

**Comment by chqrlie** [comment]
@lerno: static methods are not a problem since the first argument is explicitly typed.  With my proposal, the type of the first argument is inferred to *pointer to struct* if not specified. 

@bvdberg: good point about constness!

`const` propagation is very important for * Should help to avoid common mistakes*. 

C++ has a simple solution for this: inserting a `const` keyword between the argument list and the method body.  I am not sure I like that better than an explicit declaration of the object pointer argument.

**Comment by bvdberg** [comment]
Hmm looking at C++ for advise is like looking at Microsoft on how to make good products. ;) .. In my opinion C++ is the worst language of all time and it gets worse every update.
Randomly adding keywords somewhere (like C++) is not a path I would want.

Currently C2 does not have a lot of implicit stuff. I thought about making the first argument implicit and calling it 'this' or something, but it didn't feel right. Currently it's a bit more typing, but explicit. It only in the definition (that is in one place in C2). Using module namespaces you can make the Type name shorter, so not DatabaseListener, but Listener also.

I'll stuck to the current version, while agreeing that it's a bit cumbersome.

**Comment by chqrlie** [comment]
> Hmm looking at C++ for advise is like looking at Microsoft on how to make good products. ;) .. In my opinion C++ is the worst language of all time and it gets worse every update. Randomly adding keywords somewhere (like C++) is not a path I would want.

I couldn't agree more!

> Currently C2 does not have a lot of implicit stuff. I thought about making the first argument implicit and calling it 'this' or something, but it didn't feel right. Currently it's a bit more typing, but explicit. It only in the definition (that is in one place in C2). Using module namespaces you can make the Type name shorter, so not DatabaseListener, but Listener also.

Yes, as I started coding in C2 to make it work on my M2 macbook, I tend to agree.

> I'll stuck to the current version, while agreeing that it's a bit cumbersome.

The point about removing the `void` return type is a separate issue, but what is your take on it?

**Comment by bvdberg** [comment]
I prefer explicit over implicit, so if a function doesn't return anything, it should just return void.
Me OCD parses files better that way
