### ISSUE TITLE
Simplifications in `switch` statements

### ISSUE THREAD

**Issue by chqrlie** [c2lang/c2compiler#131]
I find it annoying to have to type `fallthrough` after each `case` clause that does not have any code.

This idiom is very common is not error-prone.  Requiring a `return`, `break` or `fallthrough` between code and the nest `case` is a blessing, but I don't see an advantage in requiring the `fallthrough` for empty `case` clauses. It makes code unnecessarily verbose and goes against the philosophy: *Should be easy to learn for C programmers*

Regarding the exception where you allow noreturn function calls to miss the `break` statement, I would propose an alternative: add a `noreturn` statement to make it explicit (and tested in debug builds) that a given function does not return. This would make the syntax more consistent and give the casual reader visual clues about such function calls.

The syntax would be: `noreturn exit(1);` or `exit(1); noreturn;`

**Comment by bvdberg** [comment]
I completely agree, good idea. I'll implement this once i have time
