### ISSUE TITLE
Range syntax in `switch` statements

### ISSUE THREAD

**Issue by chqrlie** [c2lang/c2compiler#133]
The range syntax using `-` is problematic:

* It only works for `enum` types
* even for `enum` values, it prevents the use of expressions that may make sense: adding or subtracting `1` is a meaningful operation to get the next or previous `enum` value, provided it exists as can be checked at compile time.
* it is inconsistent with the common extension implemented in gcc and clang.

Why not use the `..` operator to express inclusive ranges?

eg: `case 'A'..'Z': return Action.IDENT;`

The same syntax could be used in initializers:
```
const u8[128] Identifier_char = {
    ['0'..'9'] = 1,
    ['A'..'Z'] = 1,
    ['_'] = 1,
    ['a'..'z'] = 1,
}
```

**Comment by bvdberg** [comment]
I think you have a valid point for switch cases. Currently there is no '..' token, only a '.' and '...' (for varargs).
case '0'...'9', 12:
instead of
case '0'-'9', 12:

Adding a '..' token seems like overkill . ..
Or did you propose : dot space dot?

**Comment by chqrlie** [comment]
> I think you have a valid point for `switch` cases. Currently there is no '..' token, only a '.' and '...' (for varargs). case '0'...'9', 12: instead of case '0'-'9', 12:

Both gcc and clang have a `..` token to mean an inclusive range of integer values in `case` expressions. This syntax might even make its way into the C Standard at some point.  Using `...` is confusing as some other languages have attached different semantics: first boundary included and second boundary excluded.

> Adding a '..' token seems like overkill . .. Or did you propose : dot space dot?

Adding a `..` does not seem overkill to me and is necessary for `0..9` to be parsed as `0`, `..`, `9`. With dot dot, you would get `0.` and `.9` and dot space dot is counter intuitive and would require extra spaces before and after in case the range boundaries are integer literals.

**Comment by bvdberg** [comment]
Implemented (website documentation will be updated this evening)

**Comment by chqrlie** [comment]
Thanks for fixing this.  Should I file a discussion or new issues for the other suggestions:
* allowing the range syntax for `switch` on integer values.
* supporting the range syntax for initializers.
* supporting the range syntax for assignments, eg:
    * ``array[0..9] = 0;`` which is much less error prone than `memset`
    * ``a[0..9] = b[0..9];`` which is much less error prone than `memcpy` and more compact than a loop.

The last item is actually a special case of slices.  Do you have a plan to support these?

**Comment by chqrlie** [comment]
> All these have proven to work nicely in C3. Note though that typically you want `a[0..9] = b[0..9]` to use memmove, as you can't be sure they're not overlapping.

Nice indeed, how about `a[0,1] = a[1,0];` to swap elements safely?

**Comment by bvdberg** [comment]
I'm not in favor of adding these fancy language constructs. They complicate the language and you never know exactly on a given architecture how it's implemented, so most programmers will than avoid it (as I would). Swapping could be done by (inline) function or manually, that also makes it easier to read. It's very easy to read over the swap above

**Comment by chqrlie** [comment]
As an afterthought on this subject, I think I was mistaken in specifying `..` as a range marker.  We should use `...` instead.

The rationale is the syntax `case 1 ... 3:` is already supported by both **gcc** and **clang** and will be included in the next version of the C Standard.  If we add existing extensions to the C language, we should use the same syntax unless there is a compelling reason not to.

**Comment by bvdberg** [comment]
Sure, I agree
