### ISSUE TITLE
c2c unable to compile on Ubuntu

### ISSUE THREAD

**Issue by grd** [c2lang/c2compiler#15]
Error messages:

Linking CXX executable c2c
libc2core.a(C2Builder.cpp.o): In function `C2::C2Builder::build()':
/home/user/llvm_build/c2compiler/c2c/Builder/C2Builder.cpp:(.text._ZN2C29C2Builder5buildEv+0x5a4): undefined reference to`llvm::sys::getDefaultTargetTriple()'
libc2core.a(C2Parser.cpp.o): In function `C2::C2Parser::ParseVarDef(bool)':
/home/user/llvm_build/c2compiler/c2c/Parser/C2Parser.cpp:(.text._ZN2C28C2Parser11ParseVarDefEb+0x213): undefined reference to`clang::Lexer::getSpelling(clang::Token const&, clang::SourceManager const&, clang::LangOptions const&, bool_)'
libc2core.a(C2Parser.cpp.o): In function `C2::C2Parser::ExpectAndConsumeSemi(unsigned int)':
/home/user/llvm_build/c2compiler/c2c/Parser/C2Parser.cpp:(.text._ZN2C28C2Parser20ExpectAndConsumeSemiEj+0x165): undefined reference to`clang::Lexer::getSpelling(clang::Token const&, clang::SourceManager const&, clang::LangOptions const&, bool_)'
libc2core.a(C2Parser.cpp.o): In function `C2::C2Parser::ParseInitValues()':
/home/user/llvm_build/c2compiler/c2c/Parser/C2Parser.cpp:(.text._ZN2C28C2Parser15ParseInitValuesEv+0x2ae): undefined reference to`clang::Lexer::getSpelling(clang::Token const&, clang::SourceManager const&, clang::LangOptions const&, bool_)'
libc2core.a(FileAnalyser.cpp.o): In function `C2::FileAnalyser::resolveEnumConstants()':
/home/user/llvm_build/c2compiler/c2c/Analyser/FileAnalyser.cpp:(.text._ZN2C212FileAnalyser20resolveEnumConstantsEv+0x3ee): undefined reference to`llvm::APInt::toString(unsigned int, bool) const'
libc2core.a(FunctionAnalyser.cpp.o): In function `C2::FunctionAnalyser::analyseDesignatorInitExpr(C2::Expr_, C2::QualType)':
/home/user/llvm_build/c2compiler/c2c/Analyser/FunctionAnalyser.cpp:(.text._ZN2C216FunctionAnalyser25analyseDesignatorInitExprEPNS_4ExprENS_8QualTypeE+0x496): undefined reference to `llvm::APInt::toString(unsigned int, bool) const'
libc2core.a(FunctionAnalyser.cpp.o): In function`C2::FunctionAnalyser::checkArrayDesignators(C2::InitListExpr_, long_)':
/home/user/llvm_build/c2compiler/c2c/Analyser/FunctionAnalyser.cpp:(.text._ZN2C216FunctionAnalyser21checkArrayDesignatorsEPNS_12InitListExprEPl+0x6d4): undefined reference to `llvm::APInt::toString(unsigned int, bool) const'
libc2core.a(FunctionAnalyser.cpp.o): In function`C2::FunctionAnalyser::analyseBitOffsetIndex(C2::Expr_, llvm::APSInt_, C2::BuiltinType_)':
/home/user/llvm_build/c2compiler/c2c/Analyser/FunctionAnalyser.cpp:(.text._ZN2C216FunctionAnalyser21analyseBitOffsetIndexEPNS_4ExprEPN4llvm6APSIntEPNS_11BuiltinTypeE+0x2fa): undefined reference to `llvm::APInt::toString(unsigned int, bool) const'
/home/user/llvm_build/c2compiler/c2c/Analyser/FunctionAnalyser.cpp:(.text._ZN2C216FunctionAnalyser21analyseBitOffsetIndexEPNS_4ExprEPN4llvm6APSIntEPNS_11BuiltinTypeE+0x50a): undefined reference to`llvm::APInt::toString(unsigned int, bool) const'
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/c2c.dir/build.make:86: recipe for target 'c2c' failed
make[2]: *_\* [c2c] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/c2c.dir/all' failed
make[1]: **\* [CMakeFiles/c2c.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by bvdberg** [comment]
What did you do exactly? Did the other steps in the install.md work fine?

**Comment by grd** [comment]
I followed all steps in install.md and compiled LLVM without any warnings or errors that I have seen (it took a while). Compiling C2 went fine, except the linking stage. I am looking at ~/c2compiler/c2c/CMakeLists.txt, the "LLVM_LIBS" variable could be set incompletely or not assigned.

**Comment by luciusmagn** [comment]
Are you sure you followed the steps accordingly to your installation folder? The steps count with installation in ~/llvm-c2, but you are installing in ~/

**Comment by grd** [comment]
Actually, reading the doc, the install directory is ~/llvm_build/c2compiler/c2c/build, but that doesn't work as well. Neither does installing from ~/llvm-c2.

**Comment by luciusmagn** [comment]
c2compiler location does not matter at all (provided the user will have read & write access to said directory), the ~/llvm-c2 applies for llvm, hence the name. However if everything else fail, he is the script I assembled a while ago for easy install. It installs whole llvm in ~/llvm-c2 and c2compiler in ~/llvm-c2/c2compiler/c2c/build.

**Comment by grd** [comment]
Thanks. I will try that (and report back over a couple of hours). What's the difference from the installation doc?

**Comment by luciusmagn** [comment]
The difference is freedom. My script gives you none. It installs everything in ~/llvm-c2 and ~/llvm-c2/c2compiler regardless of where you start the script from. It automatically adds to the $PATH and properly sets $C2_LIBDIR.

Also, this is a script, Bas' install guide is a guide. :D

**Comment by bvdberg** [comment]
Ok I've installed Ubuntu 15 and tried compilation. The good news is that I'm
also running into the same problems. I'll look into it.. It will take a few
days...

**Comment by bvdberg** [comment]
I've found that that by changing the compiler from clang++ to g++ in
CMakeLists.txt  it does build.

**Comment by grd** [comment]
On Debian it builds. Two notes however: 

1) I again had to hard link to /lib/x86_64-linux-gnu/libtinfo.so.5.9 with the name /lib/x86_64-linux-gnu/libtinfo.so.
2) Maybe it is good to mention that you have to `sudo apt-get install cmake g++` prior to the installation.

**Comment by luciusmagn** [comment]
If you change the CMakeLists.txt, you can also use ncurses instead of tinfo, if you are having troubles with tinfo.

**Comment by bvdberg** [comment]
fixed
