### ISSUE TITLE
The question of the further development of the C2 compiler

### ISSUE THREAD

**Issue by EvolutionPixels** [c2lang/c2compiler#26]
Will the compiler develop more actively and what are the prospects for development in the near future?

**Comment by bvdberg** [comment]
The last months have been busy (outside C2), so development has suffered. C2 developement is far from dead however. There are still some core areas where work has been done (not published yet). These areas are: libraries and macro-system. Also the C2-examples archive has seen work, showing C2 examples (and often causing features on the C2 compiler). I'll make sure to publish the in-progress work more often.
