### ISSUE TITLE
c2c: error: cannot find library 'libc'

### ISSUE THREAD

**Issue by yngtodd** [c2lang/c2compiler#28]
Hey everyone, 

I love the project. I have a dumb question: after going through the setup and attempting to compile the hello world example, I am getting the following:

```
building target hello
c2c: error: cannot find library 'libc'
```

In my `.zshrc` I have the following:

```
export C2_LIBDIR=/Users/youngtodd/c2compiler
alias c2c=/Users/youngtodd/c2compiler/build/c2c/c2c
export CC=clang
export CXX=clang++
export PATH=$HOME/llvm-c2/bin:$PATH
```

I am sure I am doing something dumb here. Do I just need to append to my `$PATH` to point to `libc` here?

**Comment by luciusmagn** [comment]
Your C2_LIBDIR variable is wrong, it needs to be the 'c2libs' folder in
c2compiler

2018-02-02 21:48 GMT+01:00 Todd Young <notifications@github.com>:

**Comment by yngtodd** [comment]
Of course. Thank you!
