### ISSUE TITLE
Compiler crash on parsing expression

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#33]
Trace:
Assertion failed: (BitWidth == RHS.BitWidth && "Bit widths must be the same"), function operator+=, file /Users/lerno/llvm/lib/Support/APInt.cpp, line 193.

This is the expression that triggers the crash:

i32 a = ((1 << 2) + 3);

**Comment by lerno** [comment]
Looks like the error is in the FunctionAnalyzer

**Comment by bvdberg** [comment]
Fixed4. Bitshifts were not implemented yet in the LiteralAnalyser. I've only added a basic implementation of shift-left. More analysing code is needed (since we can only shift unsigned numbers)

**Comment by lerno** [comment]
@bvdberg I found it (eventually) too, but implemented the warnings as well. I assume we're fine with converting the right hand side to a 64 bit number...

**Comment by lerno** [comment]
See if you want to merge my changes.
