### ISSUE TITLE
LLVM IR generation crashes on using booleans, bitshift, bitwise operators.

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#37]
A few examples:

    i32 a = 2;
    i32 b = 10;
    if (a > 1 || (b > 4)) { return 1; }

This does *not* crash:

    i32 a = 2;
    i32 b = 10;
    if (a > 1 || b > 4) { return 1; }

More crashing things:

    i32 a = 1 + 3 * 4 << 1;
    i32 a = 1 + 3 * 4 && 1;

**Comment by bvdberg** [comment]
IR generation asserts() on TODO on almost everything except hello world...
