### ISSUE TITLE
Incorrect cast behaviour in LiteralAnalyser

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#40]
1. cast<i32>(3) => will cast the expression to a 31 bit integer.
2. cast<i32>(2147483648) => 0
3. cast<i32>(2147483647) => -1
4. cast<i32>(1073741823) = 1073741823
4. cast<i32>(1073741824) = -1073741824

The cast is using getIntegerWidth to set the resulting width, causing this issue.

**Comment by bvdberg** [comment]
Which syntax do you use exactly then? Because currently `cast` needs a generics-like argument, like:
`cast<u32>(2147483648)`

**Comment by lerno** [comment]
It's in the implicit casts in the LiteralAnalyser when mixing uXX with iXX values.

**Comment by bvdberg** [comment]
obsolete
