### ISSUE TITLE
Completely remove dependency on Clang's lexer

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#43]
1. The lexer parses a lot of stuff that C2 shouldn't, this makes the code rather unclear at places.
2. The lexer has a firm idea about how to lex certain tokens, like "@" which might complicate parsing.
3. We have full C pre-processing. I don't think this is a good thing.
4. Keywords need to be defined in the Clang source :-[
5. Code requires reading up on a lot of Clang code to see how things work, rather than just the c2compiler code.

**Comment by bvdberg** [comment]
I think replacing the Clang preprocessor/Lexer with a custom version seems nice, but it doesn't really bring anything. Language wise it changes nothing. Also Clang's lexer generates the SourceLocation's for each token. These are also used in Clang's DiagnosticsEngine. So either both need to be replaced, or a replacement Lexer would have to generate compatible ones.

I think that before doing this, we need to do a *lot* more analysis, otherwise we run the risk of ending up in a broken state..

**Comment by lerno** [comment]
It's definitely not lightly done, and I'm *absolutely not* suggesting that this is done in a single sweep. Rather, I suggest that a roadmap is drawn up to lessen direct dependency on Clang. Refactorings are done piecemeal until the dependency on Clang is completely gone. This is a slow, baby step by baby step, change.

I completely understand that you might have misunderstood me. I'm used to working in legacy code bases where it's important that the code is constantly improved, refactored etc, BUT it must always be in working condition. So changes are small, chipping away at the old and building the new step by step.

Tools in the toolbox:
1. Making wrappers
2. Relying on fewer functions
3. Auditing what parts of each class is really used.
4. Copy-paste code from Clang and use the copies instead of the normal clang classes. Then refactor these copies small pieces at a time (if necessary)

**Comment by lerno** [comment]
Just a quick update. I'm working on the 4th approach now. Making a copy of Clang's Lexer & Diagnostics + all the necessary files that are attached to it (they are MANY)

Once the lexer is part of the "normal" C2C source:

1. Remove clang as library, just depend on a vanilla llvm.
2. Strip parts not needed for the lexing / preprocessing of C2 (that's *a lot*)
3. Eventually replace the lexer and streamline the diagnostics

Already at (1), we can do any changes to keywords etc directly in the C2C source, which is a huge plus for me.

**Comment by lerno** [comment]
I managed to extract all the code to have it compile (with only name / path changes). Have a look when you have time: https://github.com/lerno/c2compiler/tree/no_clang

The next step would be to remove unused parts of the code.

**Comment by lerno** [comment]
Another checkin, this removes a lot functionality that was not needed. Modules and pragmas in particular. LanguageOptions are almost completely removed, freezing parsing at C99/C11 levels mostly.

**Comment by luciusmagn** [comment]
Hey, I just tried a clean build of C2C with pure LLVM, for old times' sake, and I can confirm that it works with just LLVM installed (I am on Arch 64-bit for reference). In my case, it means cutting down clean build time from 45-ish minutes to ~2 minutes. I am very impressed, good job.

**Comment by lerno** [comment]
Thanks for checking @luciusmagn !

**Comment by bvdberg** [comment]
@luciusmagn you just installed the LLVM binary with a package manager?
