### ISSUE TITLE
Implement C99 sparse array initialization

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#48]
In C99-compiler, it is possible to initialize a sparse array with the following syntax:

    char* foo[10000] = { [42] = "The Meaning", [13] = "Bad luck", [1999] = "Party like it's" };

    // foo[22] => NULL
    // foo[13] => "Bad luck"

**Comment by catb0t** [comment]
Isn't this just C99 designated initialisers? (C99 got them from P9?)

**Comment by lerno** [comment]
@catb0t You're right. Darn, I thought C99 only got the struct initialization. But yeah, both are from P9.

**Comment by lerno** [comment]
Embarassing, this actually works. I was making the mistake with ";" after array initialization and thought it was broken.
