### ISSUE TITLE
unary + is not pruned from AST.

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#50]
There is no need to leave the unary + in the AST, this just makes analysis a bit more difficult. Either prune it in the lexer (when doing the lexer) or prune it in the AST during parsing.

**Comment by bvdberg** [comment]
agreed

**Comment by lerno** [comment]
Note that the + operator actually has some function in C:
https://stackoverflow.com/questions/6637005/what-is-the-purpose-of-the-unary-operator-in-c

Three possibilities:
1. Remove it from the grammar
2. Make it a noop (no int promotion)
3. Use it as C does (int promotion, error on pointers with +)

**Comment by bvdberg** [comment]
Option 1 is definitely the best IMHO. I've also never seen it used anywhere.

**Comment by lerno** [comment]
The point of unary plus is that you can write something like

```
add[] = {
  +1,
  -1,
  -1,
  +1 };
```

Retaining visual symmetry. I would prefer keeping it for that reason.

**Comment by bvdberg** [comment]
If it's not in the way and just removed from the AST, fine by me.

**Comment by lerno** [comment]
Thank you. I'll close this one then.
