### ISSUE TITLE
Implement UnaryOperations in LLVM IR

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#51]
Unary Operations are not yet implemented. I'm currently working on this in a branch.

**Comment by bvdberg** [comment]
Since the Clang-patch is so big, adding more features on top of that might result in some merge conflicts in the future, unless this change is quite isolated

**Comment by lerno** [comment]
Some additions here, but not complete #60

**Comment by bvdberg** [comment]
same as previous issue
