### ISSUE TITLE
Wiki is locked

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#54]
Could perhaps we open the wiki for documentation collaboration again?

**Comment by bvdberg** [comment]
I think it's very weird that anyone can edit that Wiki. I don't want just anyone being able to change things, that will cost me too much time to check/fix.

**Comment by lerno** [comment]
Can we perhaps get a list of contributors that CAN edit the wiki?

**Comment by lerno** [comment]
Isn't it possible to add members to the c2lang team that does not have write access? https://help.github.com/articles/repository-permission-levels-for-an-organization/

Look through the table. Members that have "read" access can edit the wiki but not approve pull requests or write to the repo. Wouldn't that be a suitable access?
