### ISSUE TITLE
Style all (non-clang) code with clang-format

### ISSUE THREAD

**Issue by bvdberg** [c2lang/c2compiler#63]
Does anyone see issues with the current .clang-format file?

**Comment by lerno** [comment]
I'll have a look. Appears that there's a plugin for AppCode that swaps the auto format of AppCode with Clang.

**Comment by bvdberg** [comment]
What do you mean with adding a passage?

I meant using clang-format for the c2c code written in c++, not using it to style c2 code. For c2 I think
we need to create a c2format or c2style tool.

**Comment by lerno** [comment]
A few bugs:

`SmallVector <IdentifierInfo *, 32> Parameters` => `SmallVector < IdentifierInfo * , 32 > Parameters`
`IdentifierInfo* II` and `IdentifierInfo *II` => `IdentifierInfo * II`

    do {
        foo();
    } while (true);

Became

    do {
        foo();
    }
    while (true);

There might be more.

**Comment by lerno** [comment]
I mean add some text on the github wiki or in the docs about it.

By the way, is there a way to get wiki access? I was thinking of documenting the parser as I go along.

**Comment by luciusmagn** [comment]
Yea, you either need to open the wiki for everyone to edit, or add those people as collaborators

**Comment by lerno** [comment]
Are collaborators the only ones that can be assigned to tasks as well? It's a bit weird not being able to get assigned to something you're working on.

**Comment by luciusmagn** [comment]
@lerno Yeah, one can only assign the owner, collaborators or organization members afaik, on Github

**Comment by lerno** [comment]
@bvdberg I humbly pray for a different switch format. I find

```
switch (foo) {
case 1:
}
```

Inconsistent (the only construct that doesn't respect indent!) and near impossible to read (can't rely on indent to see where we are)

I know the idea is that case is a label (**so it does not create a new scope** – unlike C2!), but I really think there is a huge readability loss. The 4 characters you gain horizontally isn't enough to pay for it.

(I also indent labels, but labels are not common enough for it to become a problem for me, although I suggest C2 code style would be indenting labels as well. Consider defer where the labels inside the defer cannot be jumped to. It would be unsuitable to use them without indent.

**Comment by lerno** [comment]
Clang style is still 3 spaces? @bvdberg

**Comment by bvdberg** [comment]
I updated the clang-format file to 4 spaces instead of 3. That matches the current code better and I think 4 spaces is easier on the eyes...
