### ISSUE TITLE
sub-struct initialization fails

### ISSUE THREAD

**Issue by bvdberg** [c2lang/c2compiler#64]
The analysis pass of the following code fails:
```
type T struct {
    i32 i;
    union {
        u32 u;
        void* p;
    }
}

T t1 = { 10, .u=20 }     // error: field designator 'u' does not refer to any field in type '(struct)T'
```

Mixing designated initializers with non-designated ones seems to be allowed in C for substructs.
The Analyzer also needs to search sub-structs/unions and keep track of what's initialized as well

**Comment by bvdberg** [comment]
I think it's best to force designated initializers for unions, so the following should fail:
```
T t4 = { 10, 20 }
```
So for unions, never implicitly initialize the first member if not specified.

**Comment by bvdberg** [comment]
I've added 2 skipped tests:
test/Init/init_sub_union_field_designator.c2 and test/Init/init_union_non_designator.c2

**Comment by lerno** [comment]
Working on it

**Comment by bvdberg** [comment]
Yes, I've already added some comments in the code as well. It requires some refactoring of struct analysis. I'm on it, but it is a bit nasty indeed.

**Comment by bvdberg** [comment]
I think that it's better to always initialize a union with a designator init. Otherwise changing the order of
the fields changes which field is initialized (by default C takes the first field)

**Comment by lerno** [comment]
Just document it, it's a significant change from C.

**Comment by bvdberg** [comment]
I've put this on the Wiki/roadmap

**Comment by lerno** [comment]
You’re still working on the sub-struct initializers or? Because I made some progress towards it at least.

**Comment by bvdberg** [comment]
I've not implemented it yet, just toying with some ideas first...
What have you written?

**Comment by lerno** [comment]
I did the refactoring needed, then added some support but incomplete because it was a bit difficult. It’s also a lot about getting into the code itself and knowing how it’s put together. The analysis passes might be nice in terms of separation, but it obfuscates the state quite a bit and it’s hard to know where things fit at ”what is known” at different times in the compiler. Single pass is so much easier to reason about.

**Comment by lerno** [comment]
Looking at it now.

**Comment by lerno** [comment]
Fixed in pull req #70

**Comment by lerno** [comment]
I removed another assert that apparently was resolved already.

**Comment by lerno** [comment]
Do we have any other errors in this now @bvdberg ?

**Comment by bvdberg** [comment]
All the code is in master currently right?  And all unit tests now pass correctly!
