### ISSUE TITLE
"Adopt" llvm classes to reduce compile time dependency on external packages

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#77]
C2 uses a handful of LLVM classes outside of IR generation. One of those is the APInt class.

My suggestion is that these classes be copied into the C2 repo under a different namespace (and possibly also name). This allows us to strip the class to what we use and releases us from internal dependencies on LLVMs quickly changing codebase.

**Comment by bvdberg** [comment]
I think those classes might be very handy for IR generation. So we can remove them now, but that just brings work in the future.

**Comment by lerno** [comment]
I didn't mean they should be removed, I mean they should be copied.

**Comment by bvdberg** [comment]
There will be a dependency on LLVM anyways, so let's not copy files unneeded

**Comment by lerno** [comment]
But the dependency on LLVM IR is quite different from LLVM classes.

**Comment by bvdberg** [comment]
Not really, they both depend on public header files and link to LLVM libs.
