### ISSUE TITLE
Types and values not checked correctly

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#80]
This is possible:

```
Foo foo = Foo;
```

Because we do not check during assignment whether Foo an expression-type or an expression with the type Foo.

**Comment by luciusmagn** [comment]
tell me, for the sport, what does it compile to? (as in, if it produces any C code) :smiley:

**Comment by lerno** [comment]
Compiles to `test_Foo foo = test_Foo`

**Comment by lerno** [comment]
Btw I enabled sizeof(Foo.x) where x is a member of Foo. So I first saw this when it swallowed i32 a = Foo.a for exactly the same reasons. I thought it was my code that had the problem but it was a general bug.

But I actually think it would be good to be able have types as first class constructs. I wrote about it in the forum.

**Comment by bvdberg** [comment]
You mean base types? (as first class constructs)

Foo.a should just be an error if a is a real member and not a struct
function.

**Comment by lerno** [comment]
No, I mean that the type could be manipulated as an entity and assigned to variables.

”Foo.a” is treated as a reference to the member of Foo called ”a”.

For offset, we can then use offset(Foo.a) instead of offset(Foo, a), it also made sizeof(Foo.a) simple to do.

So the error for i32 a = Foo.a should be ”cannot assign struct member type to i32”


/C
