### ISSUE TITLE
Invalid expression assignment is not detected by analyser

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#83]
This code is accepted by the analyser but is not valid C.

    a = argc + 1 = 1;

**Comment by bvdberg** [comment]
Indeed. We have to extend the analyses to check for these situations. What these 'situations'
are exactly I'm not sure about.

**Comment by lerno** [comment]
I have a pretty good idea, but it touches code that is affected by the open pull requests, so any fixes need to wait.

**Comment by bvdberg** [comment]
fixed :)
