### ISSUE TITLE
Type.cpp missing a few AST descriptions

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#85]
Struct, Enum, Function and ModuleType is missing debug descriptions.

I think @bvdberg is best suited to decide what should go into those.

**Comment by bvdberg** [comment]
What is missing exactly? Is the debug print of the AST incomplete?

**Comment by lerno** [comment]
In some cases the debug printout has a TODO in it. It’s very unclear to me what’s missing (and probably other contributors would be similarly confused.

I’m on a quest investigating all of the todos so we can get most of them closed as they sometimes come back to haunt you when implementing/fixing something unrelated.

**Comment by lerno** [comment]
For this, it’s just debug printouts that needs to have their todos resolved.

**Comment by bvdberg** [comment]
There's a lot of (minor) stuff missing. But we have quite some coverage with unit tests, so that's okey. So any new functionality will also have to be supported by tests.

**Comment by lerno** [comment]
Can we please not close these unless done? The whole point was to have a list of things that’s needed to do. Unless you just fixed it in a check in. This issue should stay until resolved.

**Comment by lerno** [comment]
:D I promise. The point of opening this one was that I didn't feel able to resolve it myself. I was unsure what you were planning in terms of extending the debug information. If there was a bit of discussion / docs around the TODO / functionality – or it is actually breaking functionality, then I can just go ahead and fix it.

**Comment by bvdberg** [comment]
obsolete
