### ISSUE TITLE
Introduce pointer-sized usize isize keywords

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#88]
usize and isize should correspond to the bitsize of a void* pointer.

**Comment by bvdberg** [comment]
exactly. They can be used to store pointer values. isize can be used to do pointer manipulation

**Comment by lerno** [comment]
I filed this so that it can be assigned a milestone. Same should be done with the rest that’s on the roadmap.

**Comment by bvdberg** [comment]
fixed
