### ISSUE TITLE
Constant expressions fail in types on global level

### ISSUE THREAD

**Issue by lerno** [c2lang/c2compiler#99]
```
module test;

const i32 FOO = 2;
type Foo i32[FOO + 1];

public func i32 main(i32 argc, i8*[] argv)  { return 0; }
```

This construct causes a crash.

**Comment by bvdberg** [comment]
Parsing + Analysing seems fine on master. C-code generation crashes indeed.

**Comment by lerno** [comment]
Exactly, constant folding needs to be a priority moving further along. When doing constant folding it's also important to open up for macros, since macros are evaluated at the same time. For example this should be valid:

`type Foo i32[@macro_something()]`

**Comment by bvdberg** [comment]
Ik was playing around with some macro options, but having non-textual macros does open up a Lot of questions. I'll open a separate issue for those discussions on the forum.

**Comment by bvdberg** [comment]
fixed
